version: "3.9"

services:

  db:
    image: postgres:16
    container_name: projeto_postgres
    restart: always
    environment:
      POSTGRES_DB: projeto
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projeto-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: projeto_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projeto
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - projeto-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: projeto_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - projeto-network

volumes:
  postgres_data:

networks:
  projeto-network:
    driver: bridge
